/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 05-Jan-2022 15:05:57
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\MATLAB\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
   0.009974726636333, -0.03833394460209,     0.05676259683, -0.03833394460209,
   0.009974726636333
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.849826046791,    5.688203849557,   -3.816962873623,
     0.9830011607069
};
