/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
 * Generated on: 18-Dec-2021 14:28:17
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 4
 * Denominator Length  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * F:\MATLAB\extern\include\tmwtypes.h 
 */
const int NL = 4;
const real64_T NUM[4] = {
    0.01379348564724,-0.009563608593466,-0.009563608593466,  0.01379348564724
};
const int DL = 4;
const real64_T DEN[4] = {
                   1,   -2.699286943033,    2.484870605052,  -0.7771239079117
};
